export const GET_ALL_AUCTIONS = 'GET_ALL_AUCTIONS';
export const SET_IS_LOADING_AUCTIONS_LIST = 'SET_IS_LOADING_AUCTIONS_LIST';
export const SET_CAR_INFO = 'SET_CAR_INFO';
export const SET_IS_LOADING_CAR_INFO = 'SET_IS_LOADING_CAR_INFO';
